@startuml graph
digraph diag {
  node [style="rounded,filled", shape=box]
  "Início" -> "Configuração de Ambiente:3"
  "Início" -> "Introdução ao Typescript:5"
  "Início" -> "Revisão do P5:3"
  "Introdução ao Typescript:5" -> "Classes e Objetos:3"
  "Introdução ao Typescript:5" -> "Arrays:3"
  "Introdução ao Typescript:5" -> "Agregação e Composição:3"
  "Agregação e Composição:3" -> "Agregação:3"
  "Arrays:3" -> "Algoritmos em Vetores - Estressados Busca:2"
  "Início" -> "Trabalhando com Testes:4"
  "Configuração de Ambiente:3" [fillcolor=lime]
  "Introdução ao Typescript:5" [fillcolor=lime]
  "Revisão do P5:3" [fillcolor=lime]
  "Classes e Objetos:3" [fillcolor=lime]
  "Arrays:3" [fillcolor=lime]
  "Agregação e Composição:3" [fillcolor=lime]
  "Agregação:3" [fillcolor=lime]
  "Algoritmos em Vetores - Estressados Busca:2" [fillcolor=lime]
  "Trabalhando com Testes:4" [fillcolor=lime]
  subgraph cluster_Início  {
    label="Início "
    style=filled
    color=lightgray
    "Configuração de Ambiente:3"
    "Introdução ao Typescript:5"
    "Revisão do P5:3"
  }
  subgraph cluster_Poo - Programação Orientada a Objetos  {
    label="Poo - Programação Orientada a Objetos "
    style=filled
    color=lightgray
    "Classes e Objetos:3"
    "Arrays:3"
    "Agregação e Composição:3"
    "Agregação:3"
    "Algoritmos em Vetores - Estressados Busca:2"
    "Trabalhando com Testes:4"
  }
}
@enduml
